#include "mags\boltblaster_pistol_mag.hpp"
#include "mags\d200_mag.hpp"
#include "mags\dc15sa_mag.hpp"
#include "mags\dc17s_dual_mag.hpp"
#include "mags\dc17s_mag.hpp"
#include "mags\dymek_pistol_mag.hpp"
#include "mags\ec17_mag.hpp"
#include "mags\rk3_mag.hpp"
#include "mags\rskf44_mag.hpp"
#include "mags\s5_mag.hpp"
#include "mags\se14c_mag.hpp"
#include "mags\se14r_mag.hpp"
#include "mags\t20_pistol_mag.hpp"
#include "mags\westar35sa_mag.hpp"

#include "mags\dc19sa_mag.hpp"