class Attachments {
    MACRO_WHITELIST(MTI_pointerIR_noModel);
    MACRO_WHITELIST(JLTS_DC17SA_flashlight);
    MACRO_WHITELIST(MTI_flashlight_noModel);
    MACRO_WHITELIST(SWLW_Westar35SA_flash);
    MACRO_WHITELIST(SWLW_Westar35SA_laser);

    MACRO_WHITELIST(MTI_Holosight_red);
    MACRO_WHITELIST(MTI_HMRD_blu);
    MACRO_WHITELIST(MTI_HMRD_red);
    MACRO_WHITELIST(3AS_Imp_Optic_1);
    MACRO_WHITELIST(optic_tws_mg);
    MACRO_WHITELIST(optic_SOS);
    MACRO_WHITELIST(optic_MRCO);
    MACRO_WHITELIST(MTI_HRCO_blu);
    MACRO_WHITELIST(MTI_HMRCO_blu);
    MACRO_WHITELIST(optic_tws);
    MACRO_WHITELIST(MTI_HRCO_red);
    MACRO_WHITELIST(MTI_HDMS_blu);
    MACRO_WHITELIST(optic_Arco);
    MACRO_WHITELIST(MTI_HRCO_grn);
    MACRO_WHITELIST(MTI_HMRCO_red);
    MACRO_WHITELIST(MTI_Holosight_blu);
    MACRO_WHITELIST(3AS_Imp_Optic_E11);
    MACRO_WHITELIST(optic_ACO_grn);
    MACRO_WHITELIST(3AS_S5_Scope);
    MACRO_WHITELIST(optic_Nightstalker);
    MACRO_WHITELIST(optic_Aco);
    MACRO_WHITELIST(optic_Holosight_smg);
    MACRO_WHITELIST(MTI_Holosight_grn);
    MACRO_WHITELIST(SWLW_Westar35S_scope);
    MACRO_WHITELIST(WM_SE14C_Scope);
    MACRO_WHITELIST(MTI_EE2_scope);
    MACRO_WHITELIST(MTI_HDMS_red);
    MACRO_WHITELIST(optic_Hamr);
    MACRO_WHITELIST(optic_LRPS);
    MACRO_WHITELIST(optic_ACO_grn_smg);
    MACRO_WHITELIST(MTI_HDMS_grn);
    MACRO_WHITELIST(MTI_HMRCO_grn);
    MACRO_WHITELIST(MTI_HMRD_grn);
    MACRO_WHITELIST(3AS_Imp_Optic_4);
    MACRO_WHITELIST(SFA_Holosight_blue);
    MACRO_WHITELIST(3AS_Imp_Optic_3);
    MACRO_WHITELIST(optic_NVS);
    MACRO_WHITELIST(optic_DMS);
    MACRO_WHITELIST(3AS_Imp_Optic_2);
    MACRO_WHITELIST(optic_Aco_smg);
    MACRO_WHITELIST(optic_Holosight);

    MACRO_WHITELIST(bipod_02_F_blk);
    MACRO_WHITELIST(bipod_01_F_blk);
    MACRO_WHITELIST(bipod_03_F_blk);
    MACRO_WHITELIST(3AS_Bipod_VK38X_f);
    MACRO_WHITELIST(3AS_Bipod_DC15L_f);

    MACRO_WHITELIST(MTI_DC15LE_muzzle);
};

class Backpacks {};

class Goggles {};

class Headgear {};

class Items {
    MACRO_WHITELIST(ItemCompass);
    MACRO_WHITELIST(JLTS_clone_comlink);
    MACRO_WHITELIST(ItemGPS);
    MACRO_WHITELIST(ItemMap);
    MACRO_WHITELIST(ItemWatch);
    MACRO_WHITELIST(ACE_Altimeter);
    MACRO_WHITELIST(ACE_SpraypaintRed);
    MACRO_WHITELIST(LRG_axe);
    MACRO_WHITELIST(MTI_Symoxin);
    MACRO_WHITELIST(ACE_splint);
    MACRO_WHITELIST(MTI_Latheniol);
    MACRO_WHITELIST(ACE_bloodIV_500);
    MACRO_WHITELIST(MTI_BactaSpray);
    MACRO_WHITELIST(ACE_DefusalKit);
    MACRO_WHITELIST(MTI_catTab_MicroDAGR);
    MACRO_WHITELIST(ACE_bloodIV_250);
    MACRO_WHITELIST(MTI_Detector);
    MACRO_WHITELIST(MTI_catTab_HCam);
    MACRO_WHITELIST(mti_flags_red);
    MACRO_WHITELIST(ACE_tourniquet);
    MACRO_WHITELIST(MTI_PBA);
    MACRO_WHITELIST(ACE_EntrenchingTool);
    MACRO_WHITELIST(ACE_packingBandage);
    MACRO_WHITELIST(MTI_catTab_tablet);
    MACRO_WHITELIST(MTI_CableTie_Light);
    MACRO_WHITELIST(MTI_Clacker);
    MACRO_WHITELIST(MTI_Nevastrin8);
    MACRO_WHITELIST(ACE_bodyBag_blue);
    MACRO_WHITELIST(ACE_quikclot);
    MACRO_WHITELIST(MTI_catTab_phone);
    MACRO_WHITELIST(ACE_fieldDressing);
    MACRO_WHITELIST(MTI_BactaPatch);
    MACRO_WHITELIST(MTI_Deraformine);
    MACRO_WHITELIST(MTI_Batroxobine);
    MACRO_WHITELIST(ACE_elasticBandage);
    MACRO_WHITELIST(ACE_wirecutter);
    MACRO_WHITELIST(ACE_surgicalKit);
    MACRO_WHITELIST(ACE_SpraypaintBlue);
    MACRO_WHITELIST(MTI_Medisensor);
    MACRO_WHITELIST(ACE_bodyBag);
    MACRO_WHITELIST(MTI_AllKitTool);
    MACRO_WHITELIST(ACE_morphine);
    MACRO_WHITELIST(ACE_MapTools);
    MACRO_WHITELIST(ACE_bloodIV);
    MACRO_WHITELIST(MTI_CableTie_Heavy);
    MACRO_WHITELIST(MTI_CableTie_Medium);
    MACRO_WHITELIST(ACE_SpraypaintGreen);
    MACRO_WHITELIST(ACE_Clacker);
    MACRO_WHITELIST(ACE_bodyBag_white);
    MACRO_WHITELIST(mti_tech_spike);
    MACRO_WHITELIST(ACE_SpraypaintBlack);
    MACRO_WHITELIST(ACE_Flashlight_XL50);
    MACRO_WHITELIST(ACE_epinephrine);
    MACRO_WHITELIST(mti_flags_blue);
};

class Magazines {
    MACRO_WHITELIST(MTI_EmergencyFlare);
    MACRO_WHITELIST(MTI_SmokeWhite_impact);
    MACRO_WHITELIST(MTI_SmokeGreen);
    MACRO_WHITELIST(MTI_ThermalDetonator);
    MACRO_WHITELIST(ls_mag_glowrod_hiRed);
    MACRO_WHITELIST(ls_mag_glowrod_hiWhite);
    MACRO_WHITELIST(MTI_Grenade_Halothane);
    MACRO_WHITELIST(MTI_SmokeBlue);
    MACRO_WHITELIST(MTI_SonicDet);
    MACRO_WHITELIST(MTI_SmokePurple_impact);
    MACRO_WHITELIST(MTI_SmokeRed_impact);
    MACRO_WHITELIST(MTI_SmokeYellow_impact);
    MACRO_WHITELIST(MTI_SmokeRed);
    MACRO_WHITELIST(MTI_MED_Mag);
    MACRO_WHITELIST(MTI_SmokePurple);
    MACRO_WHITELIST(ACE_HandFlare_Green);
    MACRO_WHITELIST(ls_mag_glowrod_hiGreen);
    MACRO_WHITELIST(ls_mag_glowrod_hiBlue);
    MACRO_WHITELIST(MTI_SmokeOrange);
    MACRO_WHITELIST(MTI_SmokeBlack);
    MACRO_WHITELIST(MTI_HandFlare_Orange);
    MACRO_WHITELIST(ACE_HandFlare_Red);
    MACRO_WHITELIST(MTI_SmokeGreen_impact);
    MACRO_WHITELIST(JLTS_grenade_emp_mag);
    MACRO_WHITELIST(ACE_HandFlare_White);
    MACRO_WHITELIST(ls_mag_glowrod_hiOrange);
    MACRO_WHITELIST(ACE_M14);
    MACRO_WHITELIST(MTI_HandFlare_Blue);
    MACRO_WHITELIST(MTI_HandFlare_Purple);
    MACRO_WHITELIST(MTI_BaradiumCore);
    MACRO_WHITELIST(MTI_SmokeBlack_impact);
    MACRO_WHITELIST(MTI_SmokeWhite);
    MACRO_WHITELIST(ShieldGrenade_Mag);
    MACRO_WHITELIST(MTI_SmokeBlue_impact);
    MACRO_WHITELIST(MTI_SmokeOrange_impact);

    MACRO_WHITELIST(MTI_DetPack);
    MACRO_WHITELIST(MTI_EC01);
    MACRO_WHITELIST(APERSMineDispenser_Mag);
    MACRO_WHITELIST(ClaymoreDirectionalMine_Remote_Mag);
};

class Uniforms {};

class Vests {};

class Weapons {};
