class CfgVehicles {
    MACRO_GH_PREAMBLE;

    MACRO_GH_WEAPON(GWEAPON(a280),"[TEA] A-280");
    MACRO_GH_WEAPON(GWEAPON(acpa),"[TEA] ACP-A");
    MACRO_GH_WEAPON(GWEAPON(acpr),"[TEA] ACP-R");
    MACRO_GH_WEAPON(GWEAPON(arkanian_carbine),"[TEA] Arkanian Carbine");
    MACRO_GH_WEAPON(GWEAPON(arkanian_rifle),"[TEA] Arkanian Rifle");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_carbine),"[TEA] Boltblaster Mk2 Carbine");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_pistol),"[TEA] Boltblaster Mk2 Pistol");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_rifle),"[TEA] Boltblaster Mk2 Rifle");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_sniper),"[TEA] Boltblaster Mk2 Sniper");
    MACRO_GH_WEAPON(GWEAPON(causality),"[TEA] Causality");
    MACRO_GH_WEAPON(GWEAPON(cd35),"[TEA] CD-35");
    MACRO_GH_WEAPON(GWEAPON(clone_knife),"[TEA] Clone Knife");
    MACRO_GH_WEAPON(GWEAPON(d200),"[TEA] D-200");
    MACRO_GH_WEAPON(GWEAPON(dc15a_gl),"[TEA] DC-15A GL");
    MACRO_GH_WEAPON(GWEAPON(dc15a),"[TEA] DC-15A");
    MACRO_GH_WEAPON(GWEAPON(dc15c_gl),"[TEA] DC-15C GL");
    MACRO_GH_WEAPON(GWEAPON(dc15c),"[TEA] DC-15C");
    MACRO_GH_WEAPON(GWEAPON(dc15l),"[TEA] DC-15L");
    MACRO_GH_WEAPON(GWEAPON(dc15le),"[TEA] DC-15LE");
    MACRO_GH_WEAPON(GWEAPON(dc15s),"[TEA] DC-15S");
    MACRO_GH_WEAPON(GWEAPON(dc15sa),"[TEA] DC-15s");
    MACRO_GH_WEAPON(GWEAPON(dc15x),"[TEA] DC-15X");
    MACRO_GH_WEAPON(GWEAPON(dc17s_dual),"[TEA] DC-17s (Dual)");
    MACRO_GH_WEAPON(GWEAPON(dc17s),"[TEA] DC-17s");
    MACRO_GH_WEAPON(GWEAPON(dc19sa),"[TEA] DC-19s");
    MACRO_GH_WEAPON(GWEAPON(dh17),"[TEA] DH-17");
    MACRO_GH_WEAPON(GWEAPON(dla13),"[TEA] DLA-13");
    MACRO_GH_WEAPON(GWEAPON(dla13c_nostock),"[TEA] DLA-13C (No Stock)");
    MACRO_GH_WEAPON(GWEAPON(dla13c),"[TEA] DLA-13C");
    MACRO_GH_WEAPON(GWEAPON(dlt19),"[TEA] DLT-19");
    MACRO_GH_WEAPON(GWEAPON(dlt19x),"[TEA] DLT-19X");
    MACRO_GH_WEAPON(GWEAPON(dp23),"[TEA] DP-23");
    MACRO_GH_WEAPON(GWEAPON(dw32s),"[TEA] DW-32S");
    MACRO_GH_WEAPON(GWEAPON(dymek_pistol),"[TEA] Dymek Pistol");
    MACRO_GH_WEAPON(GWEAPON(e11_gl),"[TEA] E-11 GL");
    MACRO_GH_WEAPON(GWEAPON(e11_stock),"[TEA] E-11 (Stock)");
    MACRO_GH_WEAPON(GWEAPON(e11),"[TEA] E-11");
    MACRO_GH_WEAPON(GWEAPON(e11d),"[TEA] E-11D");
    MACRO_GH_WEAPON(GWEAPON(e15),"[TEA] E-15");
    MACRO_GH_WEAPON(GWEAPON(ec17),"[TEA] EC-17");
    MACRO_GH_WEAPON(GWEAPON(ee2),"[TEA] EE-2");
    MACRO_GH_WEAPON(GWEAPON(el34),"[TEA] EL-34");
    MACRO_GH_WEAPON(GWEAPON(electrostaff),"[TEA] Electrostaff");
    MACRO_GH_WEAPON(GWEAPON(epl2),"[TEA] EPL-2");
    MACRO_GH_WEAPON(GWEAPON(guard_shock_pike),"[TEA] Guard Shock Pike");
    MACRO_GH_WEAPON(GWEAPON(heavy_sword),"[TEA] Heavy Sword");
    MACRO_GH_WEAPON(GWEAPON(ls150),"[TEA] LS-150");
    MACRO_GH_WEAPON(GWEAPON(mpl),"[TEA] MPL");
    MACRO_GH_WEAPON(GWEAPON(plx1),"[TEA] PLX-1");
    MACRO_GH_WEAPON(GWEAPON(rd4),"[TEA] RD-4");
    MACRO_GH_WEAPON(GWEAPON(rk3),"[TEA] RK-3");
    MACRO_GH_WEAPON(GWEAPON(rps6_d_loaded),"[TEA] RPS-6 (Disposable)");
    MACRO_GH_WEAPON(GWEAPON(rps6_hp),"[TEA] RPS-6 Heavy Projectile");
    MACRO_GH_WEAPON(GWEAPON(rps6),"[TEA] RPS-6");
    MACRO_GH_WEAPON(GWEAPON(rskf44),"[TEA] RSKF-44");
    MACRO_GH_WEAPON(GWEAPON(s5),"[TEA] S-5");
    MACRO_GH_WEAPON(GWEAPON(s7),"[TEA] S-7");
    MACRO_GH_WEAPON(GWEAPON(se14c),"[TEA] SE-14c");
    MACRO_GH_WEAPON(GWEAPON(se14r),"[TEA] SE-14r");
    MACRO_GH_WEAPON(GWEAPON(skirata_knife),"[TEA] Skirata Knife");
    MACRO_GH_WEAPON(GWEAPON(t20_ac),"[TEA] T-20 Assault Cannon");
    MACRO_GH_WEAPON(GWEAPON(t20_pistol),"[TEA] T-20 Pistol");
    MACRO_GH_WEAPON(GWEAPON(t20_rifle),"[TEA] T-20 Rifle");
    MACRO_GH_WEAPON(GWEAPON(t21),"[TEA] T-21");
    MACRO_GH_WEAPON(GWEAPON(valken38x),"[TEA] Valken 38X");
    MACRO_GH_WEAPON(GWEAPON(verpine),"[TEA] Verpine Shatter Rifle");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_1),"[TEA] Vibroblade #1");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_2),"[TEA] Vibroblade #2");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_3),"[TEA] Vibroblade #3");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_4),"[TEA] Vibroblade #4");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_5),"[TEA] Vibroblade #5");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_6),"[TEA] Vibroblade #6");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_7),"[TEA] Vibroblade #7");
    MACRO_GH_WEAPON(GWEAPON(vibrospear),"[TEA] Vibrospear");
    MACRO_GH_WEAPON(GWEAPON(westar35c),"[TEA] Westar-35C");
    MACRO_GH_WEAPON(GWEAPON(westar35s),"[TEA] Westar-35S");
    MACRO_GH_WEAPON(GWEAPON(westar35sa),"[TEA] Westar-35s");
    MACRO_GH_WEAPON(GWEAPON(westarm5_gl),"[TEA] Westar-M5 GL");
    MACRO_GH_WEAPON(GWEAPON(westarm5),"[TEA] Westar-M5");
    MACRO_GH_WEAPON(GWEAPON(x300),"[TEA] X-300");
    MACRO_GH_WEAPON(GWEAPON(z6_small),"[TEA] Z-6");
    MACRO_GH_WEAPON(GWEAPON(z6),"[TEA] Z-6");
    MACRO_GH_WEAPON(GWEAPON(zh73),"[TEA] ZH-73");
};
