class CfgVehicles {
    MACRO_GH_PREAMBLE;

    MACRO_GH_WEAPON(GWEAPON(a280),"[ENC] A-280");
    MACRO_GH_WEAPON(GWEAPON(acpa),"[ENC] ACP-A");
    MACRO_GH_WEAPON(GWEAPON(acpr),"[ENC] ACP-R");
    MACRO_GH_WEAPON(GWEAPON(arkanian_carbine),"[ENC] Arkanian Carbine");
    MACRO_GH_WEAPON(GWEAPON(arkanian_rifle),"[ENC] Arkanian Rifle");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_carbine),"[ENC] Boltblaster Mk2 Carbine");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_pistol),"[ENC] Boltblaster Mk2 Pistol");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_rifle),"[ENC] Boltblaster Mk2 Rifle");
    MACRO_GH_WEAPON(GWEAPON(boltblaster_sniper),"[ENC] Boltblaster Mk2 Sniper");
    MACRO_GH_WEAPON(GWEAPON(causality),"[ENC] Causality");
    MACRO_GH_WEAPON(GWEAPON(cd35),"[ENC] CD-35");
    MACRO_GH_WEAPON(GWEAPON(clone_knife),"[ENC] Clone Knife");
    MACRO_GH_WEAPON(GWEAPON(d200),"[ENC] D-200");
    MACRO_GH_WEAPON(GWEAPON(dc15a_gl),"[ENC] DC-15A GL");
    MACRO_GH_WEAPON(GWEAPON(dc15a),"[ENC] DC-15A");
    MACRO_GH_WEAPON(GWEAPON(dc15c_gl),"[ENC] DC-15C GL");
    MACRO_GH_WEAPON(GWEAPON(dc15c),"[ENC] DC-15C");
    MACRO_GH_WEAPON(GWEAPON(dc15l),"[ENC] DC-15L");
    MACRO_GH_WEAPON(GWEAPON(dc15le),"[ENC] DC-15LE");
    MACRO_GH_WEAPON(GWEAPON(dc15s),"[ENC] DC-15S");
    MACRO_GH_WEAPON(GWEAPON(dc15sa),"[ENC] DC-15s");
    MACRO_GH_WEAPON(GWEAPON(dc15x),"[ENC] DC-15X");
    MACRO_GH_WEAPON(GWEAPON(dc17s_dual),"[ENC] DC-17s (Dual)");
    MACRO_GH_WEAPON(GWEAPON(dc17s),"[ENC] DC-17s");
    MACRO_GH_WEAPON(GWEAPON(dc19sa),"[ENC] DC-19s");
    MACRO_GH_WEAPON(GWEAPON(dh17),"[ENC] DH-17");
    MACRO_GH_WEAPON(GWEAPON(dla13),"[ENC] DLA-13");
    MACRO_GH_WEAPON(GWEAPON(dla13c_nostock),"[ENC] DLA-13C (No Stock)");
    MACRO_GH_WEAPON(GWEAPON(dla13c),"[ENC] DLA-13C");
    MACRO_GH_WEAPON(GWEAPON(dlt19),"[ENC] DLT-19");
    MACRO_GH_WEAPON(GWEAPON(dlt19x),"[ENC] DLT-19X");
    MACRO_GH_WEAPON(GWEAPON(dp23),"[ENC] DP-23");
    MACRO_GH_WEAPON(GWEAPON(dw32s),"[ENC] DW-32S");
    MACRO_GH_WEAPON(GWEAPON(dymek_pistol),"[ENC] Dymek Pistol");
    MACRO_GH_WEAPON(GWEAPON(e11_gl),"[ENC] E-11 GL");
    MACRO_GH_WEAPON(GWEAPON(e11_stock),"[ENC] E-11 (Stock)");
    MACRO_GH_WEAPON(GWEAPON(e11),"[ENC] E-11");
    MACRO_GH_WEAPON(GWEAPON(e11d),"[ENC] E-11D");
    MACRO_GH_WEAPON(GWEAPON(e15),"[ENC] E-15");
    MACRO_GH_WEAPON(GWEAPON(ec17),"[ENC] EC-17");
    MACRO_GH_WEAPON(GWEAPON(ee2),"[ENC] EE-2");
    MACRO_GH_WEAPON(GWEAPON(el34),"[ENC] EL-34");
    MACRO_GH_WEAPON(GWEAPON(electrostaff),"[ENC] Electrostaff");
    MACRO_GH_WEAPON(GWEAPON(epl2),"[ENC] EPL-2");
    MACRO_GH_WEAPON(GWEAPON(guard_shock_pike),"[ENC] Guard Shock Pike");
    MACRO_GH_WEAPON(GWEAPON(heavy_sword),"[ENC] Heavy Sword");
    MACRO_GH_WEAPON(GWEAPON(ls150),"[ENC] LS-150");
    MACRO_GH_WEAPON(GWEAPON(mpl),"[ENC] MPL");
    MACRO_GH_WEAPON(GWEAPON(plx1),"[ENC] PLX-1");
    MACRO_GH_WEAPON(GWEAPON(rd4),"[ENC] RD-4");
    MACRO_GH_WEAPON(GWEAPON(rk3),"[ENC] RK-3");
    MACRO_GH_WEAPON(GWEAPON(rps6_d_loaded),"[ENC] RPS-6 (Disposable)");
    MACRO_GH_WEAPON(GWEAPON(rps6_hp),"[ENC] RPS-6 Heavy Projectile");
    MACRO_GH_WEAPON(GWEAPON(rps6),"[ENC] RPS-6");
    MACRO_GH_WEAPON(GWEAPON(rskf44),"[ENC] RSKF-44");
    MACRO_GH_WEAPON(GWEAPON(s5),"[ENC] S-5");
    MACRO_GH_WEAPON(GWEAPON(s7),"[ENC] S-7");
    MACRO_GH_WEAPON(GWEAPON(se14c),"[ENC] SE-14c");
    MACRO_GH_WEAPON(GWEAPON(se14r),"[ENC] SE-14r");
    MACRO_GH_WEAPON(GWEAPON(skirata_knife),"[ENC] Skirata Knife");
    MACRO_GH_WEAPON(GWEAPON(t20_ac),"[ENC] T-20 Assault Cannon");
    MACRO_GH_WEAPON(GWEAPON(t20_pistol),"[ENC] T-20 Pistol");
    MACRO_GH_WEAPON(GWEAPON(t20_rifle),"[ENC] T-20 Rifle");
    MACRO_GH_WEAPON(GWEAPON(t21),"[ENC] T-21");
    MACRO_GH_WEAPON(GWEAPON(valken38x),"[ENC] Valken 38X");
    MACRO_GH_WEAPON(GWEAPON(verpine),"[ENC] Verpine Shatter Rifle");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_1),"[ENC] Vibroblade #1");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_2),"[ENC] Vibroblade #2");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_3),"[ENC] Vibroblade #3");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_4),"[ENC] Vibroblade #4");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_5),"[ENC] Vibroblade #5");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_6),"[ENC] Vibroblade #6");
    MACRO_GH_WEAPON(GWEAPON(vibroblade_7),"[ENC] Vibroblade #7");
    MACRO_GH_WEAPON(GWEAPON(vibrospear),"[ENC] Vibrospear");
    MACRO_GH_WEAPON(GWEAPON(westar35c),"[ENC] Westar-35C");
    MACRO_GH_WEAPON(GWEAPON(westar35s),"[ENC] Westar-35S");
    MACRO_GH_WEAPON(GWEAPON(westar35sa),"[ENC] Westar-35s");
    MACRO_GH_WEAPON(GWEAPON(westarm5_gl),"[ENC] Westar-M5 GL");
    MACRO_GH_WEAPON(GWEAPON(westarm5),"[ENC] Westar-M5");
    MACRO_GH_WEAPON(GWEAPON(x300),"[ENC] X-300");
    MACRO_GH_WEAPON(GWEAPON(z6_small),"[ENC] Z-6");
    MACRO_GH_WEAPON(GWEAPON(z6),"[ENC] Z-6");
    MACRO_GH_WEAPON(GWEAPON(zh73),"[ENC] ZH-73");
};
