name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT build
      run: hemtt build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: .hemttout/*
  check_paths:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .hemttout
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapbol
    - name: Run file patch checker
      run: python ./tools/check_paths.py
  cleanup_artifacts:
    needs: check_paths
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Call webhook to delete artifacts
      env:
        ARTIFACT_DELETION_WEBHOOK: ${{ secrets.ARTIFACT_DELETION_WEBHOOK }}
      run: |
        echo "::add-mask::$ARTIFACT_DELETION_WEBHOOK"
        curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $ARTIFACT_DELETION_WEBHOOK" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"